# This workflow fetches the latest RSS entry and sends notifications via Farcaster

name: RSS Fetch & Notifications

on:
  schedule:
    # Runs at 1 AM EST (6 AM UTC) to fetch the latest RSS entry
    - cron: "0 6 * * *"
    # Runs at 12 PM EST (5 PM UTC) to send notifications
    - cron: "0 17 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-latest-rss:
    name: Fetch Latest RSS Entry
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGHOST: ${{ secrets.PGHOST }}
      PGPORT: ${{ secrets.PGPORT }}
      PGUSER: ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Fetch Latest RSS Script
        run: yarn fetchLatest

  send-notifications:
    name: Send Farcaster Notifications
    runs-on: ubuntu-latest
    needs: fetch-latest-rss # Ensures RSS fetch completes first
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Send Notifications Script
        run: yarn sendNotifications
