name: Fetch Latest RSS Entry

on:
  schedule:
    - cron: "0 6 * * *" # Runs at 1 AM EST (6 AM UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-latest-rss:
    name: Fetch Latest RSS Entry
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGHOST: ${{ secrets.PGHOST }}
      PGPORT: ${{ secrets.PGPORT }}
      PGUSER: ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CLOUDFRONT_URL: ${{ secrets.CLOUDFRONT_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Fetch Latest RSS Script
        run: node scripts/fetchLatest.js
